version: "3.1"

services:
  app:
    build:
      context: .docker
      args:
        USER_ID:
        GROUP_ID:
        TIMEZONE:
    ports:
      - 8080:80
    depends_on:
      - mysql
      - elasticsearch
    env_file: .env
    volumes:
        - .:/home/app/workspace

  mysql:
    image: mysql:8.0
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - ./data/mysql:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - index.blocks.read_only_allow_delete
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data